// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neixyigpgwnlmaxqvjad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5laXh5aWdwZ3dubG1heHF2amFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjY5NDMsImV4cCI6MjA3NDYwMjk0M30.epcNmkZEOZk4-uRWiFTP_cZRc358yFwRUj0xemodMEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});